apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-service.fullname" . }}
  labels:
    {{- include "genai-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort | default 30884 }}
  selector:
    {{- include "genai-service.selectorLabels" . | nindent 4 }}
