apiVersion: v1
kind: Service
metadata:
  name: {{ include "visit-service.fullname" . }}
  labels:
    {{- include "visit-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "visit-service.selectorLabels" . | nindent 4 }}
