apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      nodePort: 30088
  selector:
    {{- include "config-server.selectorLabels" . | nindent 4 }}
