apiVersion: v1
kind: Service
metadata:
  name: {{ include "vets-service.fullname" . }}
  labels:
    {{- include "vets-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.type }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "vets-service.selectorLabels" . | nindent 4 }}
