name: Microservices with Helm

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy config-server
        run: helm upgrade --install config-server ./config-server
      - name: Port-forward config-server and check health
        shell: powershell
        run: |
          Start-Process kubectl -ArgumentList 'port-forward pod/config-server-66f664db96-55s8f 8888:8888' -NoNewWindow
          Start-Sleep -Seconds 10
          Invoke-RestMethod -Uri http://localhost:8888/actuator/health   

      - name: Deploy discovery-server
        run: helm upgrade --install discovery-server ./discovery-server

      - name: Deploy customers-service
        run: helm upgrade --install customers-service ./customers-service

      - name: Deploy visits-service
        run: helm upgrade --install visits-service ./visits-service

      - name: Deploy vets-service
        run: helm upgrade --install vets-service ./vets-service

      - name: Deploy genai-service
        run: helm upgrade --install genai-service ./genai-service

      - name: Deploy api-gateway
        run: helm upgrade --install api-gateway ./api-gateway

      - name: Deploy admin-server
        run: helm upgrade --install admin-server ./admin-server

