name: Deploy Microservices with Helm

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Allow PowerShell scripts to run in this session
      - name: Set PowerShell Execution Policy
        run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force 
        shell: powershell

      # Set up kubeconfig for kubectl and helm
      - name: Set up Kubeconfig 
        run: |
          $kubePath = "$env:USERPROFILE\.kube"
          if (-Not (Test-Path -Path $kubePath)) {
            New-Item -ItemType Directory -Path $kubePath | Out-Null
          }
          $kubeConfigContent = "${{ secrets.KUBE_CONFIG_DATA }}"
          $kubeConfigContentBytes = [System.Convert]::FromBase64String($kubeConfigContent)
          [System.IO.File]::WriteAllBytes("$kubePath\config", $kubeConfigContentBytes)

          # Remove inheritance and grant user read/write permission
          icacls "$kubePath\config" /inheritance:r
          icacls "$kubePath\config" /grant:r "${env:USERNAME}:(R,W)"
        shell: powershell

      # Docker login step
      - name: Log in to Docker Hub
        shell: powershell
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          $env:DOCKER_TOKEN | docker login -u $env:DOCKER_USERNAME --password-stdin

      # Helm deployments for each microservice
      - name: Deploy config-server
        run: helm upgrade --install config-server ./config-server --namespace default --create-namespace
        shell: powershell

      - name: Deploy discovery-server
        run: helm upgrade --install discovery-server ./discovery-server --namespace default --create-namespace
        shell: powershell

      - name: Deploy customers-service
        run: helm upgrade --install customers-service ./customers-service --namespace default --create-namespace
        shell: powershell

      - name: Deploy visits-service
        run: helm upgrade --install visits-service ./visits-service --namespace default --create-namespace
        shell: powershell

      - name: Deploy vets-service
        run: helm upgrade --install vets-service ./vets-service --namespace default --create-namespace
        shell: powershell

      - name: Deploy genai-service
        run: helm upgrade --install genai-service ./genai-service --namespace default --create-namespace
        shell: powershell

      - name: Deploy api-gateway
        run: helm upgrade --install api-gateway ./petapi-gateway --namespace default --create-namespace
        shell: powershell

      - name: Deploy admin-server
        run: helm upgrade --install admin-server ./admin-server --namespace default --create-namespace
        shell: powershell
 
