name: Deploy to EKS with Helm

on:
  push:
    branches:
      -   feature/my-eks-deploy-test # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name your-cluster-name --region ${{ secrets.AWS_REGION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy config-server
        run: helm upgrade --install config-server ./config-server

      - name: Deploy discovery-server
        run: helm upgrade --install discovery-server ./discovery-server

      - name: Deploy customers-service
        run: helm upgrade --install customers-service ./customers-service

      - name: Deploy visits-service
        run: helm upgrade --install visits-service ./visits-service

      - name: Deploy vets-service
        run: helm upgrade --install vets-service ./vets-service

      - name: Deploy genai-service
        run: helm upgrade --install genai-service ./genai-service

      - name: Deploy api-gateway
        run: helm upgrade --install api-gateway ./api-gateway

      - name: Deploy admin-server
        run: helm upgrade --install admin-server ./admin-server

