name: Microservices with Helm

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login (Windows-safe)
        shell: powershell
        run: |
          $username = "${{ secrets.DOCKER_USERNAME }}"
          $token = "${{ secrets.DOCKER_TOKEN }}"
          $secureToken = $token.Trim()  # remove any trailing newlines/spaces
          Write-Host "Logging in as $username"
          echo $secureToken | docker login -u $username --password-stdin

      - name: Deploy config-server
        run: helm upgrade --install config-server ./config-server

      - name: Deploy discovery-server
        run: helm upgrade --install discovery-server ./discovery-server

      - name: Deploy customers-service
        run: helm upgrade --install customers-service ./customers-service

      - name: Deploy visits-service
        run: helm upgrade --install visits-service ./visits-service

      - name: Deploy vets-service
        run: helm upgrade --install vets-service ./vets-service

      - name: Deploy genai-service
        run: helm upgrade --install genai-service ./genai-service

      - name: Deploy api-gateway
        run: helm upgrade --install api-gateway ./api-gateway

      - name: Deploy admin-server
        run: helm upgrade --install admin-server ./admin-server

